# 서버 설정
server:
  port: 8000
  forward-headers-strategy: framework

# Spring Application 설정
spring:
  config:
    import: optional:file:.env[.properties]
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  profiles:
    active: dev

  # Spring Cloud Gateway 설정
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      global-cors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
              - "http://13.125.94.196:8000"
            allow-credentials: true
            allowed-headers:
              - X-requested-with
              - Authorization
              - content-type
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowed-methods:
              - PUT
              - GET
              - POST
              - PATCH
              - DELETE
              - OPTIONS

      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter

        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter

        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/board-service/**
          filters:
            - StripPrefix=1
#            - JwtAuthenticationFilter

        - id: reply-service
          uri: lb://REPLY-SERVICE
          predicates:
            - Path=/reply-service/**
          filters:
            - StripPrefix=1
#            - JwtAuthenticationFilter

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1
#            - JwtAuthenticationFilter

        - id: product-read-service
          uri: lb://PRODUCT-READ-SERVICE
          predicates:
            - Path=/product-read-service/**
          filters:
            - StripPrefix=1
#            - JwtAuthenticationFilter

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/**
          filters:
            - StripPrefix=1
#            - JwtAuthenticationFilter

        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin-service/**
          filters:
            - StripPrefix=1
#            - JwtAuthenticationFilter

        - id: batch-service
          uri: lb://BATCH-SERVICE
          predicates:
            - Path=/batch-service/**
          filters:
            - StripPrefix=1
#            - JwtAuthenticationFilter

        - id: asset-service
          uri: lb://ASSET-SERVICE
          predicates:
            - Path=/asset-service/**
          filters:
            - StripPrefix=1
#            - JwtAuthenticationFilter

        - id: auction-service
          uri: lb://AUCTION-SERVICE
          predicates:
            - Path=/auction-service/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter

        - id: piece-service
          uri: lb://PIECE-SERVICE
          predicates:
            - Path=/piece-service/**
          filters:
            - StripPrefix=1
#            - JwtAuthenticationFilter

        - id: funding-service
          uri: lb://FUNDING-SERVICE
          predicates:
            - Path=/funding-service/**
          filters:
            - StripPrefix=1
#            - JwtAuthenticationFilter

        - id: alert-service
          uri: lb://ALERT-SERVICE
          predicates:
            - Path=/alert-service/**
          filters:
            - StripPrefix=1
#            - JwtAuthenticationFilter
        - id: real-time-data-service
          uri: lb://REAL-TIME-DATA-SERVICE
          predicates:
            - Path=/real-time-data-service/**
          filters:
            - StripPrefix=1
#           - JwtAuthenticationFilter

      discovery:
        locator:
          enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs  # API 문서 경로
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html

    urls:
      - url: "/product-service/v3/api-docs"
        name: "Product Service API"
      - url: "/board-service/v3/api-docs"
        name: "Board Service API"
      - url: "/auth-service/v3/api-docs"
        name: "Auth Service API"
      - url: "/member-service/v3/api-docs"
        name: "Member Service API"
      - url: "/funding-service/v3/api-docs"
        name: "Funding Service API"
      - url: "/piece-service/v3/api-docs"
        name: "Piece Service API"
      - url: "/auction-service/v3/api-docs"
        name: "Auction Service API"
      - url: "/reply-service/v3/api-docs"
        name: "Reply Service API"
      - url: "/payment-service/v3/api-docs"
        name: "Payment Service API"
      - url: "/product-read-service/v3/api-docs"
        name: "Product Read Service API"
      - url: "/batch-service/v3/api-docs"
        name: "Batch Service API"
      - url: "/real-time-data-service/v3/api-docs"
        name: "Real Time Data Service API"

JWT:
  secret-key: ${JWT_SECRET_KEY}
  token:
    access-expire-time: 1800000000
    refresh-expire-time: 1209600000